# Generated by Django 4.1.7 on 2023-03-21 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('listed_date', models.DateTimeField(verbose_name='date listed')),
                ('address_text', models.CharField(max_length=500)),
                ('email_text', models.CharField(max_length=200)),
                ('phone_text', models.CharField(max_length=200)),
                ('owner_name_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_txt', models.CharField(max_length=200)),
                ('notes_txt', models.CharField(max_length=5000)),
                ('quantity_num', models.FloatField()),
                ('units_of_measure_text', models.CharField(max_length=100)),
                ('price_num', models.FloatField()),
                ('vat_percent_num', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company_profit_percent_num', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assigned_to_txt', models.CharField(max_length=200)),
                ('progress_percent_num', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plan_start_date', models.DateField()),
                ('plan_days_num', models.FloatField()),
                ('actual_start_date', models.DateField()),
                ('actual_end_date', models.DateField()),
                ('construct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.construct')),
            ],
        ),
    ]
