# Generated by Django 4.1.1 on 2023-06-22 05:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('listed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date listed')),
                ('last_save_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last save')),
                ('address_text', models.CharField(max_length=500)),
                ('email_text', models.EmailField(default='email@domain.com', max_length=254)),
                ('phone_text', models.CharField(default='07770777', max_length=200, validators=[django.core.validators.RegexValidator(message='Only numbers and +', regex='^[+0-9]*$')])),
                ('owner_name_text', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(default='Some Team', max_length=800)),
                ('overall_progress_percent_num', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress')),
                ('vat_percent_num', models.FloatField(default='5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company_profit_percent_num', models.FloatField(default='15', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('owner_profit_coeff', models.FloatField(default='0.13', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('paid_num', models.FloatField(default='0')),
                ('struct_json', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=list.models.Invoice.get_id, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], default='IN', max_length=3)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=6)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('seller', models.CharField(max_length=100)),
                ('photo', models.ImageField(default=list.models.empty_image, upload_to='invoices/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details_txt', models.TextField(default='-')),
                ('construct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.construct')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only numbers and +', regex='^[+0-9]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_txt', models.CharField(default='', max_length=200)),
                ('to_txt', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(default='000000', max_length=100)),
                ('details_txt', models.TextField(default='-')),
                ('photo', models.ImageField(default=list.models.empty_image, upload_to='receipts/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('construct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.construct')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.construct')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.invoice')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.transaction')),
            ],
            options={
                'unique_together': {('invoice', 'transaction')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='transactions',
            field=models.ManyToManyField(through='list.InvoiceTransaction', to='list.transaction'),
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='0')),
                ('user_name', models.CharField(default='', max_length=200)),
                ('file_path', models.CharField(default='', max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('construct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.construct')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workers', models.CharField(default='Somebody', max_length=800)),
                ('name_txt', models.CharField(max_length=200)),
                ('notes_txt', models.TextField(default='-')),
                ('constructive_notes', models.TextField(default='-')),
                ('client_notes', models.TextField(default='-')),
                ('quantity_num', models.FloatField(default='1')),
                ('units_of_measure_text', models.CharField(default='-', max_length=100)),
                ('price_num', models.FloatField()),
                ('progress_percent_num', models.FloatField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('plan_start_date', models.DateField(default=django.utils.timezone.now)),
                ('plan_days_num', models.FloatField()),
                ('actual_start_date', models.DateField(default=django.utils.timezone.now)),
                ('actual_end_date', models.DateField(default=django.utils.timezone.now)),
                ('construct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.construct')),
            ],
        ),
    ]
