# Generated by Django 4.1.1 on 2023-06-22 05:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='0')),
                ('user_name', models.CharField(default='', max_length=200)),
                ('file_path', models.CharField(default='', max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('construct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.construct')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
