# Generated by Django 4.2.4 on 2023-10-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='main_contract_choice',
            field=models.BooleanField(default=False),
        ),
    ]
