# Generated by Django 4.2.4 on 2023-10-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_choice_main_contract_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=0)),
                ('color', models.CharField(default='white', max_length=200)),
                ('constructs', models.ManyToManyField(blank=True, to='list.construct')),
            ],
        ),
    ]
