# Generated by Django 4.1.7 on 2023-03-21 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_construct_overall_progress_percent_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='company_profit_percent_num',
            field=models.FloatField(default='15', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='notes_txt',
            field=models.CharField(default='-', max_length=5000),
        ),
        migrations.AlterField(
            model_name='choice',
            name='progress_percent_num',
            field=models.FloatField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='quantity_num',
            field=models.FloatField(default='1'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='units_of_measure_text',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='vat_percent_num',
            field=models.FloatField(default='5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
