# Generated by Django 4.2.4 on 2023-10-26 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='construct',
            name='deposit_percent_expect',
            field=models.FloatField(default='15', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
