# Generated by Django 4.2.4 on 2023-10-26 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construct',
            name='company_profit_percent_num',
            field=models.FloatField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='construct',
            name='deposit_percent_expect',
            field=models.FloatField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='construct',
            name='owner_profit_coeff',
            field=models.FloatField(default=0.13, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='construct',
            name='vat_percent_num',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
