# Generated by Django 4.2.4 on 2023-12-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_construct_foreman'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mismatch',
            field=models.BooleanField(default=False),
        ),
    ]
