# Generated by Django 4.2.4 on 2023-12-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_invoice_payment_mismatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
