# Generated by Django 4.2.4 on 2023-12-29 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_remove_project_client_delete_worker_delete_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='construct',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_constructs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='construct',
            name='foreman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='foreman_constructs', to=settings.AUTH_USER_MODEL),
        ),
    ]
