# Generated by Django 4.2.4 on 2024-01-15 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_construct_client_user_alter_construct_foreman'),
    ]

    operations = [
        migrations.AddField(
            model_name='construct',
            name='notes_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='construct',
            name='ontop_profit_percent_num',
            field=models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
