# Generated by Django 4.2.4 on 2024-01-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_construct_footer_txt_construct_header_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construct',
            name='footer_txt',
            field=models.TextField(blank=True, default='**Additional information:** goes here.', null=True),
        ),
        migrations.AlterField(
            model_name='construct',
            name='header_txt',
            field=models.TextField(blank=True, default='**QUOTE**\n*(this quotation will be valid until Month Day, Year)*', null=True),
        ),
    ]
