# Generated by Django 4.2.4 on 2024-05-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0015_statuschain_status_note_construct_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
