# Generated by Django 4.2.4 on 2024-05-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construct',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.status'),
        ),
    ]
