# Generated by Django 4.2.4 on 2024-05-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0017_alter_construct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuschain',
            name='color',
            field=models.CharField(default='white', max_length=200),
        ),
        migrations.AddField(
            model_name='statuschain',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
