# Generated by Django 4.2.4 on 2024-05-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_note_content_type_note_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuschain',
            options={'ordering': ['priority']},
        ),
    ]
