# Generated by Django 4.2.4 on 2024-05-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0020_alter_statuschain_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['chain__name', 'name'], 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterModelOptions(
            name='statuschain',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Status chains (categories)'},
        ),
    ]
